version: '3.9'
services:
    mysql:
        image: mysql
        ports:
            - 3306:3306
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=ProductDB
    product:
        build: .
        volumes:
            - product:/usr/src/myapp
        ports:
            - 8080:8080
        restart: always
        depends_on:
            - mysql
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ProductDB?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
volumes:
    dbdata:
    product:
